# Generated by Django 5.0 on 2024-11-06 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0002_remove_tipoactividad_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='evidencia',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='evidencias/'),
        ),
        migrations.AddField(
            model_name='evidencia',
            name='enlace',
            field=models.URLField(blank=True, null=True),
        ),
    ]
