# Generated by Django 5.0 on 2024-11-26 19:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0004_alter_informe_fecha_fin_alter_informe_fecha_inicio'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipoactividad',
            name='programa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tipos_actividades', to='actividades.programa'),
        ),
        migrations.AlterField(
            model_name='tipoactividad',
            name='nombre',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
