# Generated by Django 5.0 on 2024-11-27 05:25

import actividades.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0005_tipoactividad_programa_alter_tipoactividad_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividad',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to=actividades.models.generar_ruta_foto_actividad),
        ),
    ]
