# Generated by Django 5.0 on 2024-11-27 22:33

import django.core.serializers.json
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0006_alter_actividad_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditoriaactividad',
            name='accion_actividad',
            field=models.CharField(choices=[('CREACION', 'Creación'), ('MODIFICACION', 'Modificación'), ('ELIMINACION', 'Eliminación')], default='CREACION', max_length=50),
        ),
        migrations.AddField(
            model_name='auditoriainforme',
            name='accion_informe',
            field=models.CharField(choices=[('CREACION', 'Creación'), ('MODIFICACION', 'Modificación'), ('ELIMINACION', 'Eliminación')], default='CREACION', max_length=50),
        ),
        migrations.AddField(
            model_name='auditoriainforme',
            name='actividad',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='actividades.actividad'),
        ),
        migrations.AlterField(
            model_name='auditoriaactividad',
            name='estado_actual',
            field=models.JSONField(blank=True, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True),
        ),
        migrations.AlterField(
            model_name='auditoriaactividad',
            name='estado_anterior',
            field=models.JSONField(blank=True, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True),
        ),
        migrations.AlterField(
            model_name='auditoriainforme',
            name='estado_actual',
            field=models.JSONField(blank=True, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True),
        ),
        migrations.AlterField(
            model_name='auditoriainforme',
            name='estado_anterior',
            field=models.JSONField(blank=True, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True),
        ),
    ]
