# Generated by Django 5.0 on 2024-11-27 22:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0007_auditoriaactividad_accion_actividad_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auditoriainforme',
            name='actividad',
        ),
        migrations.AlterField(
            model_name='auditoriaactividad',
            name='actividad',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='actividades.actividad'),
        ),
        migrations.AlterField(
            model_name='auditoriainforme',
            name='informe',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='actividades.informe'),
        ),
    ]
