# Generated by Django 5.0 on 2024-11-27 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0008_remove_auditoriainforme_actividad_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auditoriaactividad',
            name='accion_actividad',
        ),
        migrations.RemoveField(
            model_name='auditoriainforme',
            name='accion_informe',
        ),
        migrations.AlterField(
            model_name='auditoriaactividad',
            name='estado_actual',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='auditoriaactividad',
            name='estado_anterior',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='auditoriainforme',
            name='estado_actual',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='auditoriainforme',
            name='estado_anterior',
            field=models.TextField(null=True),
        ),
    ]
