# Generated by Django 5.0 on 2024-11-28 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0009_remove_auditoriaactividad_accion_actividad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditoriaactividad',
            name='accion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='auditoriainforme',
            name='accion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
