# Generated by Django 5.0 on 2024-11-28 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0010_auditoriaactividad_accion_auditoriainforme_accion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditoriaactividad',
            name='accion',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='auditoriainforme',
            name='accion',
            field=models.TextField(null=True),
        ),
    ]
