# Generated by Django 5.0 on 2024-11-28 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0012_remove_auditoriaactividad_estado_actual_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditoriaactividad',
            name='estado_actual',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='auditoriaactividad',
            name='estado_anterior',
            field=models.TextField(null=True),
        ),
    ]
