# Generated by Django 5.0 on 2024-11-28 21:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0013_auditoriaactividad_estado_actual_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditoriaactividad',
            name='actividad',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='actividades.actividad'),
        ),
        migrations.AlterField(
            model_name='auditoriainforme',
            name='informe',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='actividades.informe'),
        ),
    ]
