# Generated by Django 5.0 on 2024-11-05 23:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('actividades', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_firma', models.ImageField(blank=True, null=True, upload_to='firmas/')),
                ('img_usuario', models.ImageField(blank=True, null=True, upload_to='perfil/')),
                ('programa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='actividades.programa')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
