# Generated by Django 5.0 on 2024-11-27 07:11

import autenticacion.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilusuario',
            name='img_firma',
            field=models.ImageField(blank=True, null=True, upload_to=autenticacion.models.generar_ruta_foto_firma),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='img_usuario',
            field=models.ImageField(blank=True, null=True, upload_to=autenticacion.models.generar_ruta_foto_perfil),
        ),
    ]
