# Generated by Django 5.0 on 2024-11-28 17:51

import autenticacion.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacion', '0002_alter_perfilusuario_img_firma_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilusuario',
            name='img_firma',
            field=models.ImageField(default='default/sin_firmar.png', upload_to=autenticacion.models.generar_ruta_foto_firma),
        ),
    ]
